version: 2.1
orbs:
  nx: nrwl/nx@1.4.0

jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
      - image: cimg/postgres:10.17
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
          POSTGRES_HOST_AUTH_METHOD: 'trust'
    resource_class: large
    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    steps:
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "yarn.lock" }}
      - nx/set-shas

      - run:
          name: Run tests
          command: ./bin/ci

workflows:
  build:
    jobs:
      - main
